# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'WordPress-Aztec-iOS', :git => 'https://github.com/wordpress-mobile/AztecEditor-iOS.git', :commit =>'f6e0e800f8fa3a9173a3927c6e914b2a154e8299'

  target 'exampleTests' do
    inherit! :search_paths

    # Pods for testing
  end

end
